### ISSUE TITLE
Diagram plugin breaks with grafana 7.3.x upgrade

### ISSUE THREAD

**Issue by ShilpaSivanesan** [jdbranham/grafana-diagram#181] opened 2021-01-22 07:31 UTC
Diagram Plugin  versions (1.7.1 and 1.6.4) breaks with **error: property map not found** with grafana 7.3.x versions

**Comment by jgarciadelanoceda** [comment] 2021-01-29 08:56
Same happens to us.
If we install via grafana-cli it installs 1.6.2 version and we have more than one mermaid in a Dashboard and mermaids are mixed.

![image](https://user-images.githubusercontent.com/6615999/106253661-0f474c00-6218-11eb-9878-364d0265163f.png)

We upload Grafana from 4.6.2 version to 7.3.7. In version 4.6.2 mermaid are not being mixed

**Comment by mjiderhamn** [comment] 2021-02-08 16:05
Duplicate of #177

**Comment by jdbranham** [comment] 2021-04-21 15:55
closing for duplicate

**Closed by jdbranham** 2021-04-21 15:55 UTC
